name: develop

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://gmzfkx6b99.hk.aircode.run/deploy
          webhook_secret: ''
          data: '{ "storehouse": "chengfeng-blog" }'
